apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://airflow.apache.org
    name: airflow
    version: 1.0.0
  values:
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
        value: "True"
      - name: "AIRFLOW__KUBERNETES__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
        value: "apache/airflow"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
        value: "2.3.3-python3.7"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "50000"
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "True"
    executor: "KubernetesExecutor"
    images:
      airflow:
        repository: apache/airflow
        tag: 2.3.3-python3.7
        pullPolicy: IfNotPresent
        pullSecret: ""
        uid: 50000
        gid: 0
    dags:
      persistence:
        enabled: false
      gitSync:
        enabled: true
        repo: https://github.com/kobe73er/airflow-dags.git
        branch: master
        maxFailures: 0
        subPath: ""
        wait: 60
