apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://airflow.apache.org
    name: airflow
    version: 1.6.0
  values:
    images:
      airflow:
        repository: "344008713423.dkr.ecr.ap-southeast-1.amazonaws.com/my-airflow"
        tag: "csdgw98"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
        value: "True"
      - name: "AIRFLOW__KUBERNETES__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
        value: "344008713423.dkr.ecr.ap-southeast-1.amazonaws.com/my-airflow"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
        value: "csdgw98"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "50000"
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
    executor: "KubernetesExecutor"
    dags:
      persistence:
        enabled: false
      gitSync:
        enabled: true
        repo: git@github.com:kobe73er/airflow-private-dags.git
        branch: master
        maxFailures: 0
        subPath: ""
        wait: 60
        sshKeySecret: "airflow-ssh-git-secret"
